# Generated by Django 3.0.8 on 2020-11-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Is Active'), ('complete', 'Complete'), ('not_active', 'N.A')], default='active', max_length=20),
        ),
    ]
